name: shourk_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  file_picker: ^10.2.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  intl: ^0.18.1
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  provider: ^6.1.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  image_picker_web: ^2.0.0
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  camera: ^0.10.0+1
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg

    - assets/images/home.jpg
    - assets/images/career.jpg
    - assets/images/wellness.jpg
    - assets/images/fashion.jpg
    - assets/images/Shourk_logo.png