class ExpertModel {
  final String id;
  final String firstName;
  final String lastName;
  final String? title;
  final String? photoFile;
  final double averageRating;
  final String? experience;
  final double price;
  final String? about;
  final List<String> strengths;
  final Map<String, List<String>> whatToExpect;
  final List<ReviewModel> reviews;
  final String category;
  final bool freeSessionEnabled;
  final bool charityEnabled;
  final int charityPercentage;

  ExpertModel({
    required this.id,
    required this.firstName,
    required this.lastName,
    this.title,
    this.photoFile,
    required this.averageRating,
    this.experience,
    required this.price,
    this.about,
    required this.strengths,
    required this.whatToExpect,
    required this.reviews,
    required this.category,
    required this.freeSessionEnabled,
    required this.charityEnabled,
    required this.charityPercentage,
  });

  String get name => '$firstName $lastName';
  double get rating => averageRating;
  
  String get imageUrl {
    if (photoFile == null) return 'assets/images/default_avatar.jpg';
    if (photoFile!.startsWith('http')) return photoFile!;
    if (photoFile!.startsWith('assets/')) return photoFile!;
    return 'https://amd-api.code4bharat.com$photoFile';
  }

  String get description => experience ?? '';

  factory ExpertModel.fromJson(Map<String, dynamic> json) {
    return ExpertModel(
      id: json['_id'] ?? '',
      firstName: json['firstName'] ?? '',
      lastName: json['lastName'] ?? '',
      title: json['title'],
      photoFile: json['photoFile'],
      averageRating: (json['averageRating'] ?? 0).toDouble(),
      experience: json['experience'],
      price: (json['price'] ?? 0).toDouble(),
      about: json['about'],
      strengths: List<String>.from(json['strengths'] ?? []),
      whatToExpect: Map<String, List<String>>.from(
        json['whatToExpect']?.map((key, value) => 
          MapEntry(key, List<String>.from(value))) ?? {},
      ),
      reviews: (json['reviews'] as List<dynamic>?)
          ?.map((review) => ReviewModel.fromJson(review))
          .toList() ?? [],
      category: json['category'] ?? '',
      freeSessionEnabled: json['freeSessionEnabled'] ?? false,
      charityEnabled: json['charityEnabled'] ?? false,
      charityPercentage: json['charityPercentage'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      '_id': id,
      'firstName': firstName,
      'lastName': lastName,
      'title': title,
      'photoFile': photoFile,
      'averageRating': averageRating,
      'experience': experience,
      'price': price,
      'about': about,
      'strengths': strengths,
      'whatToExpect': whatToExpect,
      'reviews': reviews.map((review) => review.toJson()).toList(),
      'category': category,
      'freeSessionEnabled': freeSessionEnabled,
      'charityEnabled': charityEnabled,
      'charityPercentage': charityPercentage,
    };
  }
}

class ReviewModel {
  final String reviewerName;
  final String reviewerTitle;
  final String reviewerImage;
  final double rating;
  final String comment;

  ReviewModel({
    required this.reviewerName,
    required this.reviewerTitle,
    required this.reviewerImage,
    required this.rating,
    required this.comment,
  });

  factory ReviewModel.fromJson(Map<String, dynamic> json) {
    return ReviewModel(
      reviewerName: json['reviewerName'] ?? '',
      reviewerTitle: json['reviewerTitle'] ?? '',
      reviewerImage: json['reviewerImage'] ?? '',
      rating: (json['rating'] ?? 0).toDouble(),
      comment: json['comment'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'reviewerName': reviewerName,
      'reviewerTitle': reviewerTitle,
      'reviewerImage': reviewerImage,
      'rating': rating,
      'comment': comment,
    };
  }
}

List<ExpertModel> dummyExperts = [
  ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
  // Add all other experts in the same format
  // (Repeating all 20 entries with converted structure)
  ExpertModel(
    id: '2',
    firstName: 'Amina',
    lastName: 'Yusuf',
    title: 'Career Coach',
    photoFile: 'assets/images/img2.jpg',
    averageRating: 4.7,
    experience: 'Helping professionals grow in their careers and achieve goals.',
    price: double.infinity,
    about: 'Certified career coach with expertise in job search and interview prep.',
    strengths: ['CV Review', 'Career Transition', 'Interview Coaching'],
    whatToExpect: {
      'Quick - 15min': ['Discuss career goals', 'Resume tips'],
      'Regular - 30min': ['Personalized career advice'],
      'Extra - 45min': ['Mock interviews + Q&A'],
      'All Access - 60min': ['Full career planning session'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Sarah Ahmed',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/women/32.jpg',
        rating: 4.8,
        comment: 'She helped me land my dream job!',
      ),
    ],
    category: 'Top',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
  // Continue converting all other entries...
  ExpertModel(
    id: '3',
    firstName: 'Dr. Sara',
    lastName: 'Khan',
    title: 'Child Therapist',
    photoFile: 'assets/images/img3.jpg',
    averageRating: 4.8,
    experience: 'Expert in child psychology and behavior development support.',
    price: double.infinity,
    about: '10+ years helping kids and parents manage behavioral challenges.',
    strengths: ['Child Behavior', 'Parent Coaching', 'Emotional Growth'],
    whatToExpect: {
      'Quick - 15min': ['Short consultation for concerns'],
      'Regular - 30min': ['Child behavior assessment'],
      'Extra - 45min': ['Parent-child counseling'],
      'All Access - 60min': ['Full development strategy'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Ola Youssef',
        reviewerTitle: 'Parent',
        reviewerImage: 'https://randomuser.me/api/portraits/women/12.jpg',
        rating: 4.9,
        comment: 'Great advice for my child’s anxiety.',
      ),
    ],
    category: 'wellness',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
  ExpertModel(
    id: '4',
    firstName: 'Omar',
    lastName: 'El-Sherif',
    title: 'Financial Advisor',
    photoFile: 'assets/images/img4.jpg',
    averageRating: 4.6,
    experience: 'Guiding smart investments and personal finance strategies.',
    price: double.infinity,
    about: 'Finance expert helping individuals plan their wealth and savings.',
    strengths: ['Investments', 'Budgeting', 'Retirement Planning'],
    whatToExpect: {
      'Quick - 15min': ['Assess your financial goals'],
      'Regular - 30min': ['Review your portfolio'],
      'Extra - 45min': ['Investment strategy session'],
      'All Access - 60min': ['Complete financial roadmap'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Ali Khan',
        reviewerTitle: 'Entrepreneur',
        reviewerImage: 'https://randomuser.me/api/portraits/men/20.jpg',
        rating: 4.6,
        comment: 'Very professional and clear with advice.',
      ),
    ],
    category: 'career',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),
   ExpertModel(
    id: '1',
    firstName: 'Dr. Ahmed',
    lastName: 'Al-Sayed',
    title: 'Psychologist',
    photoFile: 'assets/images/img1.jpg',
    averageRating: 4.9,
    experience: 'hello this is short expert here and I hope that you connect with me.',
    price: double.infinity,
    about: 'Experienced psychologist with 15+ years in clinical therapy.',
    strengths: ['Mental Health', 'Therapy', 'Family Counseling'],
    whatToExpect: {
      'Quick - 15min': ['Introduction & 2 quick tips', 'Discuss primary concern'],
      'Regular - 30min': ['Explore your issues in more depth'],
      'Extra - 45min': ['In-depth mental wellness session'],
      'All Access - 60min': ['Comprehensive wellness planning'],
    },
    reviews: [
      ReviewModel(
        reviewerName: 'Cameron Williamson',
        reviewerTitle: 'Client',
        reviewerImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        rating: 5.0,
        comment: 'Super insightful session!',
      ),
    ],
    category: 'Home',
    freeSessionEnabled: false,
    charityEnabled: false,
    charityPercentage: 0,
  ),

 
];